services:
  jellyfin-wrapped:
    build:
      context: .
      args:
        VITE_JELLYFIN_URL: ${VITE_JELLYFIN_URL}
    container_name: jellyfin-wrapped
    restart: unless-stopped
    ports:
      - "3030:80"
